Envío parcial de catálogos
dgb-sistemas/biblat_process pull request #12
Opened 2018-08-14 18:41 UTC by iselagb27

2018-08-15 19:56 UTC, arturorc commented
Corregir la codificación de los .csv, deben estar en UTF-8 y creo que un mejor delimitador es el TAB

2018-08-15 19:57 UTC, arturorc requested changes
Corregir la codificación de los .csv, deben estar en UTF-8 y creo que un mejor delimitador es el TAB

2018-08-20 17:54 UTC, arturorc commented
Hay archivos duplicados, ya que algunos tiene extensión `txt` y otros `csv`, no se borraron los archivos csv o se hicieron las correcciones sobre estos, y la recomendación de la extensión para los archivos separados por tabulador es `tsv`

2018-08-20 18:01 UTC, arturorc commented
@iselagb27 la recomendación es hacer los cambios desde la línea de comandos, un `git rm` de los archivos y después el push, ahora es mejor dejar más limpio esto con un un squash
https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/
https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git
Una vez echo esto hacer un `git push origin tk11 --force`

2018-09-04 20:00 UTC, arturorc requested changes
En general el `id` si no se esta usando no veo necesario que este en los datos fuente, sugiero eliminarlo

2018-09-04 20:00 UTC, arturorc commented on datos/LicenciaCC.json
> +    "url": "https://creativecommons.org/licenses/by/4.0/legalcode"
Las URL pueden apuntar a la licencia directamente y no hasta el detalle
<https://creativecommons.org/licenses/by/4.0>~~/legalcode~~

2018-09-04 20:00 UTC, arturorc commented on datos/NombreGeografico.tsv
> +	Antillas Holandesas (para documentos históricos)	Netherlands Antilles
Creo que la ayuda entre paréntesis debe ir en otro campo y crear un issue o PR en dgb-sistemas/biblat-schema

2018-09-05 15:57 UTC, iselagb27 commented on datos/LicenciaCC.json
> +    "url": "https://creativecommons.org/licenses/by/4.0/legalcode"
Corregido

2018-09-05 15:57 UTC, iselagb27 commented on datos/NombreGeografico.tsv
> +	Antillas Holandesas (para documentos históricos)	Netherlands Antilles
Estoy de acuerdo

2018-09-10 19:22 UTC, merged